### ISSUE TITLE
Suppresion of known vulnerabilities

### ISSUE THREAD

**Issue by marwin1991** [angrymeir/SecScanner2JUnit#19]
F.e. https://github.com/jeremylong/DependencyCheck uses `dependency-check-suppression.xml`

Proposition:

We sen search for file in `.gitlab` directory f.e. `sast-config.yml`

```yml
sast:
  suppressions:
    - type: "cwe"
      value: "2555"
    - type: "find_sec_bugs_type"
      value: "SPRING_ENDPOINT"
```

Relates: https://github.com/angrymeir/SecScanner2JUnit/pull/18

**Comment by angrymeir** [comment]
I think this is a very complex problem. Not saying we shouldn't do it, just needs careful planning.

--------
#### Problem Scenario 1
One problem that directly came to my mind is the following: If we suppress findings based on `type` and `value` we potentially remove relevant findings.

Assume we have a finding at line 10 in file A of `type=cwe` and `value=2555` which we want to suppress as described in `sast-config.yml`. Now the same issue is introduced in file B (potentially containing critical code) - we will not get notified about it. 

#### Possible Solutions
Add the file location for suppression -> What if the finding occurs in the same file instead?
Add the line location for suppression -> Quickly changing, so not a reliable indicator...
Use inline comments [like Bandit does](https://bandit.readthedocs.io/en/latest/config.html#exclusions)? -> Requires parsing of the file to determine suppression

#### Alternative Solution
Use the exclusion mechanisms of scanners (e.g. [Semgrep](https://semgrep.dev/docs/ignoring-files-folders-code/), [Bandit](https://bandit.readthedocs.io/en/latest/config.html#exclusions)).  
This way its transparent to every involved stakeholder (at least at the code level) which findings should be ignored without employing a separate tool :) 

--------
#### Problem Scenario X
In addition, typical issues that arise when managing security findings are the traceability of findings throughout the development workflow (1) and the deduplication of findings (2) - since I didn't have the time to think about these two topics in the context of this proposal, both need further investigation...

**Comment by marwin1991** [comment]
@angrymeir you are right, about **Problem Scenario 1**, It should be consider to allow ignore explicite findings.

I don't know if ID could be useful ?

Generally my idea is a bit inspired by: 
https://docs.gitlab.com/ee/user/application_security/sast/customize_rulesets.html

where there more important thing is that we have some know low typ of finding like `SPRING_ENDPOINT` 
https://github.com/find-sec-bugs/find-sec-bugs/issues/212
It is only notification (https://find-sec-bugs.github.io/bugs.htm#SPRING_ENDPOINT) 
and it would be useful to ignore it.

Maybe in the first phase we allow ignoring by type and value and in the next phase we will add explicite suppresion?

**Comment by marwin1991** [comment]
You can check out my draft of draft ^^ https://github.com/angrymeir/SecScanner2JUnit/pull/20

**Comment by marwin1991** [comment]
@angrymeir If I will get your approval I will continue implementation of ignoring by type and value?

**Comment by marwin1991** [comment]
@angrymeir I have changed the name from `sast-config.yml` to `ss2ju-config.yml` in example

**Comment by marwin1991** [comment]
I have one more idea,

we do not have to skip this vulnerabilities, we can only mark them as passed

We would have to change:
```
 tc.add_failure_info(message=properties['message'], output=output, failure_type=f_type)
```

**Comment by marwin1991** [comment]
> I have one more idea,
> 
> we do not have to skip this vulnerabilities, we can only mark them as passed
> 
> We would have to change:
> 
> ```
>  tc.add_failure_info(message=properties['message'], output=output, failure_type=f_type)
> ```

@angrymeir what do you think?

**Comment by angrymeir** [comment]
Ah well I missed your latest idea before merging...

First I thought, it might be confusing when ignored vulnerabilities are displayed in the GitLab UI, but after testing this seems like a really nice idea!

GitLab handles passed tests differently in merge request and pipelines.
In merge requests it only shows the failed tests, but gives an indication for more tests

<img width="1121" alt="Screenshot 2022-09-27 at 10 20 50" src="https://user-images.githubusercontent.com/16398152/192473631-5f6163c9-35a1-4ed5-8751-7c3a93203312.png">

And in the pipelines overview, it lists all tests

<img width="1420" alt="Screenshot 2022-09-27 at 10 21 11" src="https://user-images.githubusercontent.com/16398152/192473772-3dfeedd6-1e50-4dd2-b742-59ad95ce5d22.png">

**Comment by marwin1991** [comment]
I think we could even add some information in test case name that this is ignored.

Another thing is that we case use both skipped test or passed test behaviour to mark ignored vulnerabilities

**Comment by angrymeir** [comment]
You mean something like `(Skipped due to config)`?

I think we should stick to the skipped test behaviour, since marking a test as passed implies that the vulnerability is no longer existing.

**Comment by marwin1991** [comment]
So maybe I will open new issue to address this

https://github.com/angrymeir/SecScanner2JUnit/issues/25

**Comment by angrymeir** [comment]
Gonna close this issue then :)

**Comment by frakman1** [comment]
Would it be possible to suppress an individual instance of a finding instead of the class of vulnerability as it is now (with `type` and `value`).
The gl-sast-semgrep-report.json lists unique ids for each vulnerability and I found them to be the same from one pipeline to the next. So can't we just use the `id` field as a suppression?
e.g.
![image](https://github.com/user-attachments/assets/7b2bad81-0d5f-4b17-942b-67363094a388)
Then the `.gitlab/ss2ju-config.yml` file would look like this:

```
sast:
  suppressions:
    - id: "2a42e9f3ac899975ad8d3cde7795186080a3ce07fe07c47b30a1d62040557b3b"
    - id: "3c6bcc964b43b427a28b5364ee7ce902da32c2c577fa975fa208cd4fdffc01e4"
    - <etc>

```

**Comment by marwin1991** [comment]
@frakman1 hello, great idea! I will try to implement it in the evening so maybe tomorrow it will be available
